include(CMakeParseArguments)
macro(my_macro)
		set(prefix MY_INSTALL)
		set(options OPTIONAL FAST)
		set(oneValueArgs DESTINATION RENAME)
		set(multiValueArgs TARGETS CONFIGURATIONS)
		cmake_parse_arguments("${prefix}" "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
		message("MY_INSTALL_OPTIONAL = ${MY_INSTALL_OPTIONAL}")
		message("MY_INSTALL_FALSE = ${MY_INSTALL_FALSE}")
		message("MY_INSTALL_DESTINATION = ${MY_INSTALL_DESTINATION}")
		message("MY_INSTALL_RENAME = ${MY_INSTALL_RENAME}")
		message("MY_INSTALL_TARGETS = ${MY_INSTALL_TARGETS}")
		message("MY_INSTALL_CONFIGURATIONS = ${MY_INSTALL_CONFIGURATIONS}")
		message("MY_INSTALL_UNPARSED_ARGUMENTS = ${MY_INSTALL_UNPARSED_ARGUMENTS}")
endmacro()
